#
# Message in A bottle Docker Compose file
#

version: "3.6"

services:
  db_lottery:
    image: postgres:13
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      # this is only for development purpose
      - "5342:5342"
    env_file:
      - env_file

  mib_lottery:
    <<:
      # Building the image
      &mib_lottery
      image: "mib-lottery:latest"
      volumes:
        - .:/swagger_server
      build:
        context: .
        dockerfile: Dockerfile

    ports:
      - "5000:5000"
    env_file:
      - env_file
    environment:
      - POSTGRES_HOST=db_lottery
    depends_on:
      - db_lottery
      - redis
      - migrations_lottery

  redis:
    image: "redis:alpine"
    ports:
      - "6739:6739"

  migrations_lottery:
    #
    # this service is used to apply migrations on db
    #
    <<: *mib_lottery
    command: flask db upgrade
    env_file:
      - env_file
    environment:
      - POSTGRES_HOST=db_lottery
    restart: on-failure
    depends_on:
      - db_lottery

# Declaring all volumes
volumes:
  pgdata: null # for maintaing db data
