"""empty message

Revision ID: 436fa5909136
Revises: 
Create Date: 2021-11-29 19:17:57.631629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '436fa5909136'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Lottery',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('trials', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Lottery')
    # ### end Alembic commands ###
